---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-mongodata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vk8s-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-mongodata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vk8s-storage
  resources:
    requests:
      storage: 10Gi